### ISSUE TITLE
New release that contains buffer.Bytes?

### ISSUE THREAD

**Issue by dmjones** [cznic/internal#6]
I'm trying to use `github.com/cznic/cc/v2` in a project that uses dep. Unfortunately, dep doesn't seem to spot the dependency chain: cc -> ir -> internal/buffer

I have to solve this by specifying both projects as 'required' in my `Gopkg.toml`:

```toml
required = ["github.com/cznic/ir", "github.com/cznic/internal/buffer"]
```
This causes dep to pick up v1.0.0 of `internal/buffer`, which is missing the [definition of `buffer.Bytes`](https://github.com/cznic/internal/commit/e5e1c3e9165d0a72507c2bbb0ffac1c02b8d3f7c).

I think cutting another release would solve this.

**Comment by dmjones** [comment]
Actually, forget this. I didn't realise `required` works nicely with constraints. So I solved this with:

```toml
required = ["github.com/cznic/ir", "github.com/cznic/internal/buffer"]

[[constraint]]
  branch = "master"
  name = "github.com/cznic/internal"
```
